name: doit
description: DOIT, a planner application built for all platforms.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk : ^3.7.2

dependencies:
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  permission_handler: ^11.0.1
  cupertino_icons:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true


  assets:
   - 'lib/core/ui/img/logo.png'
   - 'lib/core/ui/img/ico.png'
   - 'lib/core/ui/img/icon.png'

  fonts:
    - family: Jura
      fonts:
        - asset: "lib/core/ui/fonts/Jura/static/Jura-Regular.ttf"
   
    - family: Montserrat
      fonts:
        - asset: "lib/core/ui/fonts/Montserrat/static/Montserrat-Regular.ttf"
    
    - family: Jura-semi
      fonts:
        - asset: "lib/core/ui/fonts/Jura/static/Jura-SemiBold.ttf"
   
    - family: Montserrat-semi
      fonts:
        - asset: "lib/core/ui/fonts/Montserrat/static/Montserrat-SemiBold.ttf"
    
    - family: Jura-bold
      fonts:
        - asset: "lib/core/ui/fonts/Jura/static/Jura-Bold.ttf"
   
    - family: Montserrat-bold
      fonts:
        - asset: "lib/core/ui/fonts/Montserrat/static/Montserrat-Bold.ttf"

    - family: Jura-hbold
      fonts:
        - asset: "lib/core/ui/fonts/Jura/Jura-VariableFont_wght.ttf"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/core/ui/img/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/core/ui/img/icon.png"
  windows:
    generate: true
    image_path: "lib/core/ui/img/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/core/ui/img/icon.png"
